In [1]:
import torch

In [3]:
A = torch.tensor([[1.0, 2.0], [2.0, 4.0]], requires_grad=True)
A

tensor([[1., 2.],
        [2., 4.]], requires_grad=True)

In [8]:
U, S, V = torch.linalg.svd(A)
print("U", U)
print("S", S)
print("V", V)


U tensor([[-0.4472, -0.8944],
        [-0.8944,  0.4472]], grad_fn=<LinalgSvdBackward0>)
S tensor([5.0000e+00, 6.6134e-08], grad_fn=<LinalgSvdBackward0>)
V tensor([[-0.4472, -0.8944],
        [-0.8944,  0.4472]], grad_fn=<LinalgSvdBackward0>)


In [6]:
logdetA = torch.linalg.det(A)
logdetA
logdetA.backward()
A.grad


tensor([[0., -0.],
        [-0., 0.]])

In [9]:
A.grad

tensor([[0., -0.],
        [-0., 0.]])